### ISSUE TITLE
Any chance for a Firefox/userscript version?

### ISSUE THREAD

**Issue by Tenome** [ReformerAgent/Archive-Unblur#1]
I've tried removing them with uBlock Origin, but I haven't had any luck. Or at least, can you list the elements that I'd need to filter? Thanks.

**Comment by ReformerAgent** [comment]
Hi, you can download the add-on of Firefox from below, load it as a temporary extension if there are any errors.

[archive_unblur-1.0.zip](https://github.com/user-attachments/files/17739361/archive_unblur-1.0.zip)

**Comment by Tenome** [comment]
> Hi, you can download the add-on of Firefox from below, load it as a temporary extension if there are any errors.
> 
> [archive_unblur-1.0.zip](https://github.com/user-attachments/files/17739361/archive_unblur-1.0.zip)

Thanks, it seems to work. When I try to load it as a regular extension, though, it says that it appears to be corrupt. I have xpinstall.signatures.required set to false, Any idea how to make it load?

Edit: uBlock can block it via `archive.org##+js(json-prune-fetch-response, response.body.page_elements.uploads.hits.hits.[].fields.collection)`
